USE ${database};
CREATE TABLE IF NOT EXISTS `Roles`(
    Id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    Name VARCHAR(20) NOT NULL
   ) ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS `Users`(
    Id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    Name VARCHAR(20) NOT NULL,
    Lastname VARCHAR(20) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    NationalId VARCHAR(20) NOT NULL,
    PhoneNumber VARCHAR(20) NOT NULL,
    Password VARCHAR(100) NOT NULL,
    RegisteredDate DATETIME NOT NULL,
    RoleId INT NOT NULL,
    FOREIGN KEY (RoleId) REFERENCES Roles(Id)
    ) ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS `SecureRandomTokens`(
    Id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    TokenHash VARCHAR(100) NOT NULL,
    ExpiredDate DATETIME NOT NULL,
    Used BOOLEAN NOT NULL,
    CreatedDate DATETIME NOT NULL,
    UserId INT NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
    ) ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS `Clients`(
    Id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NationalId VARCHAR(20) NOT NULL,
    Name VARCHAR(20) NOT NULL,
    LastName VARCHAR(20) NOT NULL,
    Email VARCHAR(50) NOT NULL,
    PhoneNumber VARCHAR(20) NOT NULL,
    RegisteredDate DATETIME NOT NULL
    ) ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS `Batteries`(
    Id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ChipId VARCHAR(20) UNIQUE NOT NULL,
    WorkOrder VARCHAR(10),
    Type VARCHAR(10) NOT NULL,
    SaleDate DATETIME,
    RegisteredDate DATETIME NOT NULL,
    ClientId INT,
    FOREIGN KEY (ClientId) REFERENCES Clients(Id)
    ) ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS `Status`(
    Id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    Name VARCHAR(20) NOT NULL
    ) ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS `Reports`(
    Id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ReportState VARCHAR(10),
    ReportDate DATETIME NOT NULL,
    FileName CHAR(36) NOT NULL,
    BatteryId INT NOT NULL,
    StatusId INT NOT NULL,
    FOREIGN KEY (BatteryId) REFERENCES Batteries(Id),
    FOREIGN KEY (StatusId) REFERENCES Status(Id)
    ) ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS `MeasurementsStatus`(
    Id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    MeasurementId INT NOT NULL,
    StatusId INT NOT NULL,
    Coment VARCHAR(200) NOT NULL,
    ReportId INT NOT NULL,
    FOREIGN KEY (StatusId) REFERENCES Status(Id),
    FOREIGN KEY (ReportId) REFERENCES Reports(Id)
    ) ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS `Measurements`(
    Id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    Magnitude VARCHAR(20) NOT NULL,
    MeasurementDate DATETIME NOT NULL,
    BatteryId INT NOT NULL,
    FOREIGN KEY (BatteryId) REFERENCES Batteries(Id)
    ) ENGINE = InnoDB;
